apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Jaeger
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus-ds
    url: http://prometheus:9090
    isDefault: true
    editable: true
    orgId: 1

  - name: Jaeger
    type: jaeger
    access: proxy
    uid: jaeger-ds
    url: http://jaeger:16686
    isDefault: false
    editable: true
    orgId: 1
